### ISSUE TITLE
improve codemon listen

### ISSUE THREAD

**Issue by ankushbhardwxj** [ankingcodes/codemon#18]
After merge of #55 , codemon now creates a directory for each problem, containing `A.cpp, A.in, A.op` and inputs,outputs are fetched from codeforces website. Therefore, we need `codemon listen` to fetch inputs from `A.in` compile `A.cpp` and then display the output. 
As a last step, it should compare it with the sample outputs in `A.op` and then show if they match or not.

**Comment by ankushbhardwxj** [comment]
@Enigmage - I think you can take this one if you want to.

**Comment by Enigmage** [comment]
@ankingcodes sure, I'll try.

**Comment by Enigmage** [comment]
@ankingcodes Hey tell me what you think about this for diffed output:

![suggest](https://user-images.githubusercontent.com/53875706/102505768-677f2000-40a8-11eb-96aa-d61a34788a41.png)


The green lines in the diffed output make up the expected output from `.op` file, red ones make up the current output which does not match the expected output and white lines make up the current output which matches the expected output. The lines starting with `?` show where the difference occurs in the unmatched output.

Also I've made it so that `codemon` first checks `test_case` file for user provided custom input, if that's not there it gives a verbose message and proceeds to run with sample test cases from `.in` file.

**Comment by ankushbhardwxj** [comment]
@Enigmage - This looks great, and way better than what I pictured it to be myself. I'd like to know what have you used to generate the diff, I guess it might be the linux `diff` or maybe `git diff` ? 

That said, I think you can improve on the diff a bit more. I mean, the explanation that you gave me in the comment, is it possible to show it within the terminal. 
```
Sample testcases failed !
Current Output: - 3 1 4 1 5 9 0             # in red
                              ^
Expected Output: 3 1 4 1 5 9 2           # in green
                             ^
```
This will be the game changing feature for codemon which will make it unique from the silly sublime text setups. 
Another thing, I'd recommend you to keep text lines to the minimum. Keep messages as short as possible. This is due to the fact that users will generally keep a terminal open in half along with their code editor. probably vertically and long texts might create issues.

**Comment by Enigmage** [comment]
> I'd like to know what have you used to generate the diff, I guess it might be the linux diff or maybe git diff ?

I've used python's `difflib` library to generate the diffed output.

> I mean, the explanation that you gave me in the comment, is it possible to show it within the terminal.

Yes it is possible but I'm afraid it can make the output really crowded in certain cases, also it will disorient the blue lines with `?` and `^` that show where the differences have occurred and it will be required to manually add white-spaces in-front of the blue lines to match with the red and green lines so that `^` points to the correct place.

> I'd recommend you to keep text lines to the minimum. Keep messages as short as possible. This is due to the fact that users will generally keep a terminal open in half along with their code editor. probably vertically and long texts might create issues.

Yes I agree, will keep that in mind and try to make the messages as short and as to the point as possible.

**Comment by Enigmage** [comment]
@ankingcodes Like you said, I thought about making the diffed output more intuitive for the user without being too overcrowded and I came up with this: When test case fails, codemon will first display the current output, then after that under the heading `Changes needed` it will display the diffed output. This makes the `+` and `-` signs of the diffed output more intuitive as user will know what is the current ouptut and what is the expected output, and what to add/remove to make the output correct. For example: 

![Screenshot from 2020-12-18 17-18-12](https://user-images.githubusercontent.com/53875706/102612615-0eba9080-4157-11eb-8432-251dcec16dcd.png)

This does the job of being intuitive for the user without being too crowded, also looks good on vertically split terminal. What do you think?

**Comment by ankushbhardwxj** [comment]
@Enigmage - This looks great. We're intending codemon to be used on vertically split terminal so this is ideal. Please send in a PR for this !

**Comment by ankushbhardwxj** [comment]
@Enigmage - Are you still interested in working on this ? I've got the work done locally myself, so if you won't be making a PR, I would like to make a PR myself and get this issue done.

**Comment by Enigmage** [comment]
@ankingcodes hey sorry for the delay, I've been a little busy for the past week in some stuff but I've successfully resumed work on this issue now. There was an edge case I needed to handle and also I've added support for python. So I'm working on it just a little bit of code refactoring and testing left. Best case I'll make the PR by tonight or worst case by tomorrow night.

**Comment by Enigmage** [comment]
@ankingcodes hey I've made the PR regarding this issue, please do check it out.

**Comment by ankushbhardwxj** [comment]
@Enigmage - sorry for delay in reviewing. Don't worry I'll review this PR and will award you points tomorrow morning.
