### ISSUE TITLE
I  think a  pull request template is needed to  review Pull request more effectively and efficiently.

### ISSUE THREAD

**Issue by kumarshobhit** [ankingcodes/codemon#46]

**Comment by ankushbhardwxj** [comment]
Firstly, you should give proper heading when filing an issue. You can describe it in the comments, but the header should be straightforward and short. 
And as a maintainer, I'm okay, without a pull request template since the project is not quite huge at the moment. Thanks ! Closing this issue for now.

**Comment by kumarshobhit** [comment]
Ok noted. Thanks for the insight.
